import { FilterOptions } from "./Filterlist";

export const countrylist: FilterOptions[] = [
    {"label": "Angola", "value": "Angola"},
    {"label": "Burkina Faso", "value": "Burkina Faso"},
    {"label": "Burundi", "value": "Burundi"},
    {"label": "Benin", "value": "Benin"},
    {"label": "Botswana", "value": "Botswana"},
    {"label": "Congo (Democratic Republic of the)", "value": "Congo (Democratic Republic of the)"},
    {"label": "Central African Republic", "value": "Central African Republic"},
    {"label": "Congo", "value": "Congo"},
    {"label": "Cote d'Ivoire", "value": "Cote d'Ivoire"},
    {"label": "Cameroon", "value": "Cameroon"},
    {"label": "Cabo Verde", "value": "Cabo Verde"},
    {"label": "Djibouti", "value": "Djibouti"},
    {"label": "Algeria", "value": "Algeria"},
    {"label": "Egypt", "value": "Egypt"},
    {"label": "Western Sahara", "value": "Western Sahara"},
    {"label": "Eritrea", "value": "Eritrea"},
    {"label": "Ethiopia", "value": "Ethiopia"},
    {"label": "Gabon", "value": "Gabon"},
    {"label": "Ghana", "value": "Ghana"},
    {"label": "Gambia", "value": "Gambia"},
    {"label": "Guinea", "value": "Guinea"},
    {"label": "Equatorial Guinea", "value": "Equatorial Guinea"},
    {"label": "Guinea-Bissau", "value": "Guinea-Bissau"},
    {"label": "Kenya", "value": "Kenya"},
    {"label": "Comoros", "value": "Comoros"},
    {"label": "Liberia", "value": "Liberia"},
    {"label": "Lesotho", "value": "Lesotho"},
    {"label": "Libya", "value": "Libya"},
    {"label": "Morocco", "value": "Morocco"},
    {"label": "Madagascar", "value": "Madagascar"},
    {"label": "Mali", "value": "Mali"},
    {"label": "Mauritania", "value": "Mauritania"},
    {"label": "Mauritius", "value": "Mauritius"},
    {"label": "Malawi", "value": "Malawi"},
    {"label": "Mozambique", "value": "Mozambique"},
    {"label": "Namibia", "value": "Namibia"},
    {"label": "Niger", "value": "Niger"},
    {"label": "Nigeria", "value": "Nigeria"},
    {"label": "Reunion", "value": "Reunion"},
    {"label": "Rwanda", "value": "Rwanda"},
    {"label": "Seychelles", "value": "Seychelles"},
    {"label": "Sudan", "value": "Sudan"},
    {"label": "Saint Helena, Ascension and Tristan da Cunha", "value": "Saint Helena, Ascension and Tristan da Cunha"},
    {"label": "Sierra Leone", "value": "Sierra Leone"},
    {"label": "Senegal", "value": "Senegal"},
    {"label": "Somalia", "value": "Somalia"},
    {"label": "South Sudan", "value": "South Sudan"},
    {"label": "Sao Tome and Principe", "value": "Sao Tome and Principe"},
    {"label": "Eswatini", "value": "Eswatini"},
    {"label": "Chad", "value": "Chad"},
    {"label": "Togo", "value": "Togo"},
    {"label": "Tunisia", "value": "Tunisia"},
    {"label": "Tanzania, United Republic of", "value": "Tanzania, United Republic of"},
    {"label": "Uganda", "value": "Uganda"},
    {"label": "Mayotte", "value": "Mayotte"},
    {"label": "South Africa", "value": "South Africa"},
    {"label": "Zambia", "value": "Zambia"},
    {"label": "Zimbabwe", "value": "Zimbabwe"}
];